break /media/data/Developments/apache/log4cxx/trunk/src/main/cpp/logger.cpp:143
break /media/data/Developments/apache/log4cxx/trunk/src/main/cpp/writerappender.cpp:221
break appenderattachableimpl.cpp:66
break appenderskeleton.cpp:113
break charsetdecoder.cpp:248
break charsetdecoder.cpp:289
break charsetdecoder.cpp:326
break charsetdecoder.cpp:366
break charsetdecoder.cpp:85
break logger.cpp:124
break logger.cpp:127
break logger.cpp:133
break logger.cpp:866
break logger.cpp:87
break logger.cpp:874
break loggingevent.cpp:172
break main.cpp:13
break rollingfileappender.cpp:357
break writerappender.cpp:215
break writerappender.cpp:221
break writerappender.cpp:83
